### ISSUE TITLE
L大openwrt固件无法自启

### ISSUE THREAD

**Issue by lysssssss** [maxlicheng/luci-app-unblockmusic#27]
重启后需要手动启动，重启后日志报错如下
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at read.then.body (/usr/share/UnblockNeteaseMusic/request.js:88:64)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by lysssssss** [comment]
好吧，我自己的问题。。网络断开了。
