### ISSUE TITLE
自编译openwrt固件 插件无法启动

### ISSUE THREAD

**Issue by Gaaraly** [maxlicheng/luci-app-unblockmusic#47]
路由器ac58u，lede最新的源码，luCI包勾选此插件，刷入后无法启动。
日志如下：
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at read.then.body (/usr/share/UnblockNeteaseMusic/request.js:88:64)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by maxlicheng** [comment]
> 路由器ac58u，lede最新的源码，luCI包勾选此插件，刷入后无法启动。
> 日志如下：
> SyntaxError: Unexpected token < in JSON at position 0
> at JSON.parse ()
> at read.then.body (/usr/share/UnblockNeteaseMusic/request.js:88:64)
> at
> at process._tickCallback (internal/process/next_tick.js:188:7)

后台手动运行启动命令试试
```
node /usr/share/UnblockNeteaseMusic/app.js -p 5200 &
```

**Comment by Gaaraly** [comment]
> > 路由器ac58u，lede最新的源码，luCI包勾选此插件，刷入后无法启动。
> > 日志如下：
> > SyntaxError: Unexpected token < in JSON at position 0
> > at JSON.parse ()
> > at read.then.body (/usr/share/UnblockNeteaseMusic/request.js:88:64)
> > at
> > at process._tickCallback (internal/process/next_tick.js:188:7)
> 
> 后台手动运行启动命令试试
> 
> ```
> node /usr/share/UnblockNeteaseMusic/app.js -p 5200 &
> ```

经多次测试与我个人网络情况有关，带来麻烦请见谅
