### ISSUE TITLE
 v2.2.3 编译后无法运行

### ISSUE THREAD

**Issue by lyvivian0077** [maxlicheng/luci-app-unblockmusic#81]
出现以下错误
@maxlicheng 
```
root@OpenWrt:~# cat  /tmp/unblockmusic.log
(node:24323) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:1080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
(node:24323) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24323) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1137:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ECONNRESET',
  path: null,
  host: '59.111.179.213',
  port: 443,
  localAddress: undefined }
```

**Comment by lyvivian0077** [comment]
之后将版本降到 `luci-app-unblockmusic_v2.2.2-10_all.ipk` , 出现以下错误. 
同样 `UnblockNeteaseMusic 未运行`

```
root@OpenWrt:~# cat /tmp/unblockmusic.log
(node:5372) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:1080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
(node:5372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1137:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ECONNRESET',
  path: null,
  host: '59.111.160.195',
  port: 443,
  localAddress: undefined }
root@OpenWrt:~#
```

**Comment by lyvivian0077** [comment]
又搞了一会,发现必须把SSR关掉(海外用户回国模式),才能启动unblockmusic.
但是还有一些error.
现在正在编译 node `v12.13.0`, 安装之后看看什么情况,再来汇报结果.

node: `node_v8.10.0-3_aarch64_cortex-a53.ipk`
unblockmusic: `luci-app-unblockmusic_v2.2.3-1_all.ipk`

```
root@OpenWrt:~# cat /tmp/unblockmusic.log
(node:23628) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:1080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
(node:23628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23628) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
HTTP Server running @ http://0.0.0.0:5200
HTTPS Server running @ https://0.0.0.0:5201
root@OpenWrt:~#
```

**Comment by a88244786** [comment]
IOS端安装证书后，的确任何版本都能运行。但是电脑端，无脑使用失效了。以前都是刷完之后，电脑端无脑正常使用~

**Comment by maxlicheng** [comment]
刚提交了一个版本，2.2.3-2，你git pull编译试试。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: a88244786 <notifications@github.com&gt;
发送时间: 2019年10月30日 22:47
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic]  v2.2.3 编译后无法运行 (#81)




IOS端安装证书后，的确任何版本都能运行。但是电脑端，无脑使用失效了。以前都是刷完之后，电脑端无脑正常使用~

**Comment by a88244786** [comment]
> 刚提交了一个版本，2.2.3-2，你git pull编译试试。 发自我的iPhone
2.2.3-2，电脑端可以无脑直接使用成功了，IOS端最新版本也正常使用。安卓系统有啥方法使用最新版本吗？已知4.1.3可以正常使用

**Comment by a88244786** [comment]
> 刚提交了一个版本，2.2.3-2，你git pull编译试试。 发自我的iPhone
> […](#)


2.2.3-2，电脑端可以无脑直接使用成功了，IOS端最新版本也正常使用。安卓系统有啥方法使用最新版本吗？已知4.1.3可以正常使用

**Comment by lyvivian0077** [comment]
#### `luci-app-unblockmusic_v2.2.3-2_all.ipk`

https://github.com/maxlicheng/luci-app-unblockmusic/issues/81#issuecomment-547943419
可以正常启动,无error. 跟node版本没有关系.

#### 希望能更新一下README
当SSR为 `海外用户回国模式` 时
1. 首先停止SSR(海外用户回国模式).
2. 启动 `unblockmusic`.
3. `unblockmusic` 正常启动后,启动SSR.(好像是DNS无法解析,具体原因不详).

```
root@OpenWrt:~# cat  /tmp/unblockmusic.log
HTTP Server running @ http://0.0.0.0:5200
HTTPS Server running @ https://0.0.0.0:5201
HTTP Server running @ http://0.0.0.0:5202
root@OpenWrt:~#
```

**Comment by maxlicheng** [comment]
好的，感谢。我抽空更新一下。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lyvivian0077 <notifications@github.com&gt;
发送时间: 2019年10月31日 09:05
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic]  v2.2.3 编译后无法运行 (#81)




luci-app-unblockmusic_v2.2.3-2_all.ipk
 
#81 (comment)
 可以正常启动,无error. 跟node版本没有关系.
 
希望能更新一下README
 
当SSR为 海外用户回国模式 时
  
首先停止SSR(海外用户回国模式). 

启动 unblockmusic. 

unblockmusic 正常启动后,启动SSR.(好像是DNS无法解析,具体原因不详). 
 root@OpenWrt:~# cat  /tmp/unblockmusic.log HTTP Server running @ http://0.0.0.0:5200 HTTPS Server running @ https://0.0.0.0:5201 HTTP Server running @ http://0.0.0.0:5202 root@OpenWrt:~#
